name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: SebasCodeDeveloper
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          snake_color: "#ff2d75"
          background_color: "#0d1117"
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
